services:
  mast3r-slam:
    build: .
    container_name: mast3r-slam-container
    stdin_open: true # Keep stdin open for the container
    command: tail -f /dev/null
    tty: true # Allocate a pseudo-TTY (required for an interactive shell)
    shm_size: '2gb'  # Increase shared memory size for multiprocessing
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./scripts:/app/scripts
      - ./checkpoints:/app/checkpoints
      - ./config:/app/config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
